spring:
  application:
    name: kotlin-geode
  main:
    lazy-initialization: true


---
## Locator
spring:
  profiles:
    active: locator
  data:
    gemfire:
      cache:
        name: ${random.value}
        server:
          port: 0
---
## Client
spring:
  profiles:
    active: client
  data:
    gemfire:
      pool:
        locators: localhost[10334]